### Администратор имеет возможность добавлять новые программы
POST http://localhost:8080/admin
Content-Type: application/x-www-form-urlencoded

programme_id = 1
name = fitness
duration = 11.11.2021
level_of_training = 0

> {%
client.test("Администратор имеет возможность добавлять новые программы", function (){
  client.assert(response.status === 200, "Ожидается код '200'. Был получен код '" + response.status + "'.");
  client.assert(response.body === "Прекрасная программа, продолжай в том же духе!", "Ожидалось 'Прекрасная программа, продолжай в " +
   "том же духе!'. Было получено '" + response.body + "'.");
});
 %}

### Администратор может отслеживать срок окончания действия льгот у пользователей




### Клиент может узнать уровень сложности программ





### Клиент может отслеживать срок окончания действий своего абонемента






### Менеджер может узнать общую стоимость покупаемых клиентом программ

