###1

###2 Админ смотрит окончание льгот
GET http://localhost:8060/admin?customer_id=5

> {%
client.test("Администратор имеет возможность отслеживать срок окончания действия льгот у пользователей", function (){
    client.assert(response.status === 200, "Ожидается код '200'. Был получен код '" + response.status + "'.");
    client.assert(response.body === "01.01.2022", "Ты не можешь знать ничего о клиентах! " +
    "Было получено '" + response.body + "'.");
});
 %}

###4 Клиент смотрит окончание абонемента
GET http://localhost:8060/client?customer_id=5

> {%
client.test("Клиент имеет возможность отслеживать срок окончания действия своего абонемента", function (){
    client.assert(response.status === 200, "Ожидается код '200'. Был получен код '" + response.status + "'.");
    client.assert(response.body === "21.12.2021",
    "Не получается:( Было получено '" + response.body + "'.");
});
 %}

