### Тестирование ситуации, когда передали некорректный customer_id
GET http://localhost:8060/benefit_pass?customer_id[]=4

> {%
client.test("Тестирование ситуации, когда передали некорректный customer_id", function (){
    client.assert(response.status === 500, "Был получен код '" + response.status + "', ожидалось 500.");
    client.assert(response.contentType.mimeType === "application/json", "Было получено '" +
         response.contentType.mimeType + "', ожидалось 'application/json'.");
    client.assert(response.body["message"] === "incorrect param \"customer_id\"", "Ожидалось 'incorrect param \"customer_id\"'. " +
        "Было получено '" + response.body["message"] + "'.");
    client.assert(response.body["status"] === "fail", "Ожидался статус 'fail'. Было получено '" +
        response.body["status"] + "'.");
});
 %}

### Тестирование ситуации, когда передали некорректный sex
GET http://localhost:8060/benefit_pass?sex[]=м

> {%
client.test("Тестирование ситуации, когда передали некорректный sex", function (){
    client.assert(response.status === 500, "Был получен код '" + response.status + "', ожидалось 500.");
    client.assert(response.contentType.mimeType === "application/json", "Было получено '" +
         response.contentType.mimeType + "', ожидалось 'application/json'.");
    client.assert(response.body["message"] === "incorrect param \"sex\"", "Ожидалось 'incorrect param \"sex\"'. " +
        "Было получено '" + response.body["message"] + "'.");
    client.assert(response.body["status"] === "fail", "Ожидался статус 'fail'. Было получено '" +
        response.body["status"] + "'.");
});
 %}

### Тестирование ситуации, когда передали некорректный birthdate
GET http://localhost:8060/benefit_pass?birthdate[]=23.23.323

> {%
client.test("Тестирование ситуации, когда передали некорректный birthdate", function (){
    client.assert(response.status === 500, "Был получен код '" + response.status + "', ожидалось 500.");
    client.assert(response.contentType.mimeType === "application/json", "Было получено '" +
         response.contentType.mimeType + "', ожидалось 'application/json'.");
    client.assert(response.body["message"] === "incorrect param \"birthdate\"", "Ожидалось 'incorrect param \"birthdate\"'. " +
        "Было получено '" + response.body["message"] + "'.");
    client.assert(response.body["status"] === "fail", "Ожидался статус 'fail'. Было получено '" +
        response.body["status"] + "'.");
});
 %}

### Тестирование ситуации, когда передали некорректный phone
GET http://localhost:8060/benefit_pass?phone[]=%2B3424234234

> {%
client.test("Тестирование ситуации, когда передали некорректный phone", function (){
    client.assert(response.status === 500, "Был получен код '" + response.status + "', ожидалось 500.");
    client.assert(response.contentType.mimeType === "application/json", "Было получено '" +
         response.contentType.mimeType + "', ожидалось 'application/json'.");
    client.assert(response.body["message"] === "incorrect param \"phone\"", "Ожидалось 'incorrect param \"phone\". " +
        "Было получено '" + response.body["message"] + "'.");
    client.assert(response.body["status"] === "fail", "Ожидался статус 'fail'. Было получено '" +
        response.body["status"] + "'.");
});
 %}

### Тестирование ситуации, когда передали некорректный passport
GET http://localhost:8060/benefit_pass?passport[]=342423432

> {%
client.test("Тестирование ситуации, когда передали некорректный passport", function (){
    client.assert(response.status === 500, "Был получен код '" + response.status + "', ожидалось 500.");
    client.assert(response.contentType.mimeType === "application/json", "Было получено '" +
         response.contentType.mimeType + "', ожидалось 'application/json'.");
    client.assert(response.body["message"] === "incorrect param \"passport\"", "Ожидалось 'incorrect param \"passport\"'. " +
        "Было получено '" + response.body["message"] + "'.");
    client.assert(response.body["status"] === "fail", "Ожидался статус 'fail'. Было получено '" +
        response.body["status"] + "'.");
});
 %}

### Тестирование ситуации, когда передали некорректный full_name
GET http://localhost:8060/benefit_pass?full_name[]=Сергей Дмитриевич Попенко

> {%
client.test("Тестирование ситуации, когда передали некорректный full_name", function (){
    client.assert(response.status === 500, "Был получен код '" + response.status + "', ожидалось 500.");
    client.assert(response.contentType.mimeType === "application/json", "Было получено '" +
         response.contentType.mimeType + "', ожидалось 'application/json'.");
    client.assert(response.body["message"] === "incorrect param \"full_name\"", "Ожидалось 'incorrect param \"full_name\"'. " +
        "Было получено '" + response.body["message"] + "'.");
    client.assert(response.body["status"] === "fail", "Ожидался статус 'fail'. Было получено '" +
        response.body["status"] + "'.");
});
 %}

### Тестирование ситуации, когда передали некорректный type_benefit
GET http://localhost:8060/benefit_pass?type_benefit[]=Сергей

> {%
client.test("Тестирование ситуации, когда передали некорректный type_benefit", function (){
    client.assert(response.status === 500, "Был получен код '" + response.status + "', ожидалось 500.");
    client.assert(response.contentType.mimeType === "application/json", "Было получено '" +
         response.contentType.mimeType + "', ожидалось 'application/json'.");
    client.assert(response.body["message"] === "incorrect param \"type_benefit\"", "Ожидалось 'incorrect param \"type_benefit\"'. " +
        "Было получено '" + response.body["message"] + "'.");
    client.assert(response.body["status"] === "fail", "Ожидался статус 'fail'. Было получено '" +
        response.body["status"] + "'.");
});
 %}

### Тестирование ситуации, когда передали некорректный number_document
GET http://localhost:8060/benefit_pass?number_document[]=231213123

> {%
client.test("Тестирование ситуации, когда передали некорректный number_document", function (){
    client.assert(response.status === 500, "Был получен код '" + response.status + "', ожидалось 500.");
    client.assert(response.contentType.mimeType === "application/json", "Было получено '" +
         response.contentType.mimeType + "', ожидалось 'application/json'.");
    client.assert(response.body["message"] === "incorrect param \"number_document\"", "Ожидалось 'incorrect param \"number_document\"'. " +
        "Было получено '" + response.body["message"] + "'.");
    client.assert(response.body["status"] === "fail", "Ожидался статус 'fail'. Было получено '" +
        response.body["status"] + "'.");
});
 %}

### Тестирование ситуации, когда передали некорректный end
GET http://localhost:8060/benefit_pass?end[]=34.342.32

> {%
client.test("Тестирование ситуации, когда передали некорректный end", function (){
    client.assert(response.status === 500, "Был получен код '" + response.status + "', ожидалось 500.");
    client.assert(response.contentType.mimeType === "application/json", "Было получено '" +
         response.contentType.mimeType + "', ожидалось 'application/json'.");
    client.assert(response.body["message"] === "incorrect param \"end\"", "Ожидалось 'incorrect param \"end\"'. " +
        "Было получено '" + response.body["message"] + "'.");
    client.assert(response.body["status"] === "fail", "Ожидался статус 'fail'. Было получено '" +
        response.body["status"] + "'.");
});
 %}


