### Тестирование ситуации, когда передали некорректный pass_id
GET http://localhost:8020/pass?pass_id[]=3

> {%
 client.test("Тестирование ситуации, когда передали некорректный pass_id", function (){
    client.assert(response.status === 500, "Был получен код '" + response.status + "', ожидалось 500.");
    client.assert(response.contentType.mimeType === "application/json", "Было получено '" +
         response.contentType.mimeType + "', ожидалось 'application/json'.");
    client.assert(response.body["message"] === "incorrect pass_id pass", "Ожидалось 'incorrect pass_id pass'. " +
        "Было получено '" + response.body["message"] + "'.");
    client.assert(response.body["status"] === "fail", "Ожидался статус 'fail'. Было получено '" +
        response.body["status"] + "'.");
 });
 %}

### Тестирование ситуации, когда передали некорректный duration
GET http://localhost:8020/pass?duration[]=3

> {%
 client.test("Тестирование ситуации, когда передали некорректный duration", function (){
    client.assert(response.status === 500, "Был получен код '" + response.status + "', ожидалось 500.");
    client.assert(response.contentType.mimeType === "application/json", "Было получено '" +
         response.contentType.mimeType + "', ожидалось 'application/json'.");
    client.assert(response.body["message"] === "incorrect duration pass", "Ожидалось 'incorrect duration pass'. " +
        "Было получено '" + response.body["message"] + "'.");
    client.assert(response.body["status"] === "fail", "Ожидался статус 'fail'. Было получено '" +
        response.body["status"] + "'.");
 });
 %}
